# Generated by Django 5.0.6 on 2026-06-09 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, choices=[('wrench', '🔧 Plumber'), ('bolt', '⚡ Electrician'), ('hammer', '🔨 Carpenter'), ('paint', '🎨 Painter'), ('snowflake', '❄️ AC Technician'), ('droplet', '💧 RO Water Service'), ('broom', '🧹 House Cleaning'), ('car', '🚗 Driver'), ('brick', '🧱 Mason'), ('fire', '🔥 Welder'), ('leaf', '🌿 Gardener')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('base_price', models.PositiveIntegerField(default=200, help_text='Minimum charge in ₹')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
            ],
            options={
                'verbose_name': 'Service Category',
                'verbose_name_plural': 'Service Categories',
                'db_table': 'service_categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
